### ISSUE TITLE
Stripping variables should ignore ?DVR

### ISSUE THREAD

**Issue by DBezemer** [kaltura/nginx-akamai-token-validate-module#2] opened 2015-05-09 11:14 UTC
With DVR enabled the stripping of tokens for live also strips the ?DVR which results in a broken URL when trying to serve cached fragments for Live.

The constructed URL has the following format: ?DVR?**hdnea** which obviously should have an & sign instead.

**Comment by erankor** [comment] 2015-05-09 12:31
Please paste the full URL that is broken, I want to see which protocol it is and if it's the manifest / segments. Also, if the problem is that the token is not added correctly to manifest responses, this issue should be opened under nginx-secure-token-module, not here.

**Comment by DBezemer** [comment] 2015-05-09 18:16
Example full URL:

```
https://live.vodgc.com/kLive/smil:0_t7twcl9n_all.smil/manifest.f4m?DVR/?__hdnea__=st=1431195390~exp=1431195690~acl=*~hmac=38e46dd6466227def6442f1b1b0188367df017fae06d09c52aef8836f1d0ee6d
```

If you think it belongs to nginx-secure-token-module I'll re-open the issue there.

**Comment by erankor** [comment] 2015-05-13 12:38
Closing since the issue was found to be on the manifest generation code in the Kaltura server

**Closed as completed by erankor** 2015-05-13 12:38 UTC
